### ISSUE TITLE
Update Blob URL path entries for children when we rename a directory

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#354]
Found while fixing #353, we don't have recursive rename working for directories in BlobUtils.  When we do a rename for a path, we should be dealing with the fact that all children will have the old dir name in their cached path, but attempts to access them will use the new name.

The fix needs to happen in `FilerFilesystem.rename` and `BlobUtils.rename`.

**Comment by gideonthomas** [comment]
Note that the only way you can have files in a deep dir is by calling move to. When you do the move, I think the blob urls update fine. When you rename the directory, we don't update the blob urls (we should be calling `FileSystemCache.refresh`) and the error manifests in two ways - first, if you referred to that file via it's old path in another file that is being currently rendered in the preview (for e.g. I have an `img` tag in my `index.html` file that refers to an image whose parent directory was recently renamed), it still shows up fine (because the blob url entry that exists is for the old path); and second, if you try to open the file (i tried with an image) whose parent dir you renamed, it breaks (in my case the image previewer 404'd and showed a broken link).

**Comment by humphd** [comment]
Unzipping an archive will also potentially create file in deep dirs, too.

I can't remember if ```FileSystemCache.refresh``` clears the existing entries first.  If it does, you'd also need to refresh the preview, since all the Blob URLs it uses would be deleted by this.

**Comment by evantsyferov** [comment]
I would like to work on this bug.

**Comment by gideonthomas** [comment]
go for it @evantsyferov.

@humphd do you know where this code change needs to be made? Looks like it might be in multiple places.

**Comment by humphd** [comment]
To be clear about what this bug is, and how you'd test it:

* Create a directory (right-click the filetree) named `folder`
* Add some files to the `folder/` directory (again, right click the folder), for example `folder/style.css` and `folder/script.js`.
* Rename `folder` to `folder1`

The way that our Live Preview works, we pre-render and cache files based on their path.  So we would have a cached version of a style sheet keyed on the path `folder/style.css`, but it now lives at `folder1/style.css`. 

I might be wrong about this, but I think that our bug is in here:

https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/FilerFileSystem.js#L177-L202

As you can see, we call `fs.rename()`, and after that we check to see if the rename was of a file.  As discussed above, what we should probably do is call into this code instead:

https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/FileSystemCache.js#L16-L80

`FileSystemCache.refresh` should force the cache we use to invalidate and be re-created, such that all new paths are properly recorded as keys.

After that happens, we need to tell the Live Preview window to reload, which we can probably do via the `reload` method defined here:

https://github.com/mozilla/brackets/blob/master/src/LiveDevelopment/LiveDevMultiBrowser.js#L876-L883
