### ISSUE TITLE
Highlight opened file on load

### ISSUE THREAD

**Issue by JordanTheriault** [mozilla/brackets#368]
On load, brackets does not highlight the currently open file in the filetree. On load, this file should be in a selected state.

**Comment by humphd** [comment]
Doing this turns out to be non-trivial, since the issue is that the file *is* being selected, but in the working set vs. in the file list, and we hide the working set now.  I spent a bunch of time on this, but it's not easy to force it to open the doc, select it, and not put it in the working set.  Also note that double-clicking a file will cause it to get added to the working set and highlighted there, thus losing the highlight in the file tree.

**Comment by sedge** [comment]
What if we automatically "opened" all files, showing the "working" tree and hiding the "file" one?

**Comment by humphd** [comment]
I wondered the same.  The risk is memory starvation, and startup-time increases while we load all those files into memory.

Another thought: what if we never highlighted any file, and used the filename in the editor bar to indicate what's selected.  Or maybe only something that gets selected when you right-click.  At least with this option we'll not confuse the issue.  The file tree becomes something you use to click a file, but doesn't show state.

cc @flukeout.

**Comment by humphd** [comment]
@Th30 this is a similar bug you might want to fix next.

**Comment by Th30** [comment]
Sounds good! I'll give it my all:)

**Comment by Th30** [comment]
So I spent some time testing the launching of brackets, it seems to default to index.html always. If index doesn't exist it will prioritize another index file (example, index-2), otherwise it will prioritize the alphabetical order of any .html file (seeing as it's auto organized alphabetically this would mean the top file will be the launch file.

<img width="431" alt="screen shot 2017-02-11 at 1 03 14 pm" src="https://cloud.githubusercontent.com/assets/3598286/22856177/8c382a7e-f05a-11e6-9868-b2d4bd201420.png">

I'll look further into this, but decided to post some of my process here incase someone gets a quick light bulb moment.:)

**Comment by Th30** [comment]
Ok I think I managed to fix it! :) I just need to get the RGBA colors set properly.

**Comment by Th30** [comment]
@humphd 
I'll try to get this fixed for Lab 5, unless you would like me to work on this on the side and choose another topic?

Thanks:)

**Comment by humphd** [comment]
This will also fix https://github.com/mozilla/thimble.mozilla.org/issues/634.

**Comment by Th30** [comment]
I could use some guidance as to where to start for this bug:P I've been trying for days but had some vagrant issues that took a while to fix:) @humphd

**Comment by Th30** [comment]
So Far I'm slowly tracking down how the program is starting and the state. I feel like I'm getting closer but not quite sure where I'm at yet
<img width="854" alt="screen shot 2017-03-06 at 4 14 48 pm" src="https://cloud.githubusercontent.com/assets/3598286/23630192/1e48b58e-0288-11e7-8aa7-617a8fc037c7.png">

I managed to locate the variables and paths that head towards the UI, and bramble startup session.
<img width="429" alt="screen shot 2017-03-06 at 4 16 31 pm" src="https://cloud.githubusercontent.com/assets/3598286/23630233/559e104c-0288-11e7-9c1b-880e647ec904.png">

I'll keep look through today. I'm sure there is a javascript file that triggers the sidebartheme.css somewhere here

**Comment by humphd** [comment]
First, it's important to not wait so long to start on things, because inevitably you'll have environment issues or other problems along the way, and you want to leave yourself enough room to get the work done.  This is a complex bug, and fixing it isn't the work of an hour.

Second, it's good that you're reaching out for help, and I'd encourage you to do that much, much sooner.  Trying to trace your way through code like this can be overwhelming, and having another set of eyes and people with more experience in your corner will help.

Having said all that, here is how I would attack this problem.  I would begin by studying the code related to things that I know are involved and work the way I want.  In this case, we know that we want it to look like it does when you click on it:

![screen shot 2017-03-06 at 4 23 33 pm](https://cloud.githubusercontent.com/assets/427398/23630596/b9620fa6-0289-11e7-872d-0e7211c2ad5f.png)

This is happening because of the styles here:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/stylesheets/sidebarTheme.css#L127-L132

Given this, I'd be interested to see where the `selected-node` class is being applied, and seeing if it's possible for us to trigger this same code path when the app starts.  You'll somehow want to trigger it down this code path:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/main.js#L128-L166

Perhaps the fix needs to go in the `ProjectManager` module, not there, but that is a clue about where to look.

**Comment by humphd** [comment]
One file comment: you don't need Vagrant and Thimble at all to debug and fix this issue.  You can load `http://localhost:8000/src/hosted.html` from your Brackets server to just work on the Brackets code directly.

**Comment by Th30** [comment]
Apologies for the late start, I was working on this about 2 weeks ago then I started again a couple of days ago, but was delayed. 

<img width="1202" alt="screen shot 2017-03-06 at 4 33 04 pm" src="https://cloud.githubusercontent.com/assets/3598286/23630872/9bf8a758-028a-11e7-8b09-c469c4727906.png">
I did try to check out the main.js, I've seen where the file is parsed ie.

"{"type":"bramble:init","mount":{"root":"/1/projects/2","filename":"/1/projects/2/test.html"},"state":{"fontSize":"15px","theme":"dark-theme","sidebarVisible":true,"sidebarWidth":111,"firstPaneWidth":63,"secondPaneWidth":98,"previewMode":"desktop","wordWrap":true,"allowJavaScript":true,"autoUpdate":true}}"

Which I did by creating breakpoints when loading into the project. So it seems that the: 
window.addEventListener("message", function(e) {
            var data = parseData(e.data);
            if(!data) {
                return;
            }
e is sent in with the data required to be parsed.

**Comment by humphd** [comment]
I modified your comment to use backticks.  Github will automatically format code for you, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by Th30** [comment]
Still working on this bug, I managed to narrow down where the the first file is chosen/loaded but am having a hard time finding where the css is called.

**Comment by Th30** [comment]
@humphd 

In remoteEvent.js

<img width="454" alt="screen shot 2017-03-09 at 1 06 04 pm" src="https://cloud.githubusercontent.com/assets/3598286/23763921/99298f6a-04c9-11e7-9e1c-dd6a1be7474c.png">


When ever a file is clicked on, this function is called and I got it to alert the filename.

This is called when finishStartup() is called from main.js.

**Comment by humphd** [comment]
@Th30 while doing some other work today, I noticed this code https://github.com/adobe/brackets/blob/0d1630c47fefa98269f1bb0937e22d5934749cd3/src/project/ProjectModel.js#L668-L715, which I think might solve your problem here (i.e., use this when we startup to force the file to load and become selected).

**Comment by humphd** [comment]
Also, you can see the lower-level call that hooks into react's data model here: https://github.com/adobe/brackets/blob/0d1630c47fefa98269f1bb0937e22d5934749cd3/src/project/ProjectModel.js#L1143

That's how they set a path to be selected.

**Comment by Th30** [comment]
@humphd Thank you! I'm going to check this out tonight! I was having problems earlier opening js files and terminal, it would freeze and require me to force quit. Turns out my Nand was busted and I had to replace it.

I'll be back at this code soon!

**Comment by Th30** [comment]
Just an update, still working on this. Will hopefully have a PR by Tuesday/Wednesday this week:) I think I'm close, but if I run into any problems I'll post here.

**Comment by Th30** [comment]
Hello Everyone!!!! just an updated, with @humphd I was able to narrow down the problem to here:
<img width="1309" alt="screen shot 2017-04-04 at 1 56 19 pm" src="https://cloud.githubusercontent.com/assets/3598286/24674944/61068336-194b-11e7-8052-16665880b843.png">

Here it check to see if it's in Project Manager or set working view.
<img width="197" alt="screen shot 2017-04-04 at 3 30 05 pm" src="https://cloud.githubusercontent.com/assets/3598286/24675021/9c3c184e-194b-11e7-82b2-2b394e9dd42e.png">

As can be seen in the original brackets, so I'm slowly tracing this backwards to FiletreeViewController.js, found below. _fileSelectionFocus was set to "WORKING_SET_VIEW"

<img width="696" alt="screen shot 2017-04-04 at 3 29 32 pm" src="https://cloud.githubusercontent.com/assets/3598286/24675069/ce1436d0-194b-11e7-815c-a42a3f7cbc33.png">

**Comment by Th30** [comment]
Ok I think I got it, what I ended up doing is removing and trace of Working Set view, since it's not required also cleaned and tweaked comments as needed hopefully I got everything. I've tested the code and it works well for me, I'm going to make a PR if you guys can check it out.

**Comment by Th30** [comment]
#688

**Comment by humphd** [comment]
They said it couldn't be done!
