### ISSUE TITLE
Rebase on Brackets 1.4

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#394]
The 1.4 release is out, https://github.com/adobe/brackets/releases/tag/release-1.4.  We should figure out when to rebase, and do it with enough time to find regressions once we do.

**Comment by confiks** [comment]
If you have the time: I'm wondering what parts of Brackets you needed to patch in order to make it work in the browser. I've viewed the [diff](https://github.com/adobe/brackets/compare/master...humphd:bramble) between now and the point on which you've based, but I think you can better see where the main work was in patching (or building on?) Brackets.

**Comment by humphd** [comment]
I'm planning to write an extensive set of docs on what we did to make it work, since others can use it for their browser-editor needs.  I hope to do that in Aug or early Sept.

**Comment by humphd** [comment]
Closing in favour of #569.
