### ISSUE TITLE
no indication which file or directory you're "in" using the context menu

### ISSUE THREAD

**Issue by Pomax** [mozilla/brackets#435]
When I right click in the file pane to make a new folder, there is no way to see which dir I'm already "in" via a folder highlight or the like. Similarly, if I want to delete a thing, it's hard to know what's actually going to get deleted because nothing has been highlighted, making create and delete mentally stressful operations, because they're not predictable.

**Comment by humphd** [comment]
This is actually something you might be able to help me solve: we have a bunch of issues related to this, and it's because of the hacky way we use the Bracket's file tree react component.  I need to modify how it does selection state in the UI, but I'm not as well versed on react as you.  Maybe we could look at it together some time.

**Comment by Pomax** [comment]
sounds like a plan to me.

**Comment by sedge** [comment]
I've also got some react chops, so let me know if you want more backup.

**Comment by Pomax** [comment]
is this something I can look at in this bramble code? If so... where can I start? =D

**Comment by humphd** [comment]
The code for the File Tree is in https://github.com/humphd/brackets/tree/bramble/src/project and the `FileTree*.js` files, with other bits in surrounding files.  The real issue here is that Brackets has a Working Set (i.e., files you currently have open vs. files on disk), and we hide that.  The selection is often going into the Working Set vs. file list, and I want to stop that from happening.

**Comment by humphd** [comment]
@Th30 fixed this in #574, closing.
