### ISSUE TITLE
Tabs for multiple opened files

### ISSUE THREAD

**Issue by maqboolkhan** [mozilla/brackets#482]
I love new thimble UI but one basic and simple feature is still missing which is `Tabs` for multiple opened file!! actually sidebar is too cool but it takes some space resulting less space for Editor and for Output! i know sidebar visibility can be toggle but it will be more user friendly if there are Tabs feature in **Thimble**  and i feel there is also no need of **undo** and **redo** buttons :)
Actually these are some suggestions!
Cheers!

**Comment by humphd** [comment]
I think this is a great idea in general (I'd prefer it as a developer), but not a good fit for our use case in Thimble.  I will say that there are extensions that provide this functionality, and someone could add them and alter how our UI works.

I'm going to close this, since we aren't likely to change it.  Thanks for suggesting it, though.
