### ISSUE TITLE
Rethink how we use Filetree panel to add Toolbox

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#594]
We waste a ton of space in the lower-half of the filetree:

![](https://raw.githubusercontent.com/mozilla/thimble.mozilla.org/master/screenshots/thimble.png)

Meanwhile, we have no where to put any extra buttons or UI, other than across the top of Thimble.  It would be nice to consider adding some kind of Toolbox that occupies the bottom 1/3rd or so of the Filetree, and allows extensions and Brackets itself to surface UI that doesn't belong in the editor or preview.

Brackets for desktop actually has a toolbar on the right-hand side of the editor, which we currently hide:

![](http://brackets.io/img/hero.png)

We could move that, or build something new.  Ideas, designs, code, welcome!

cc @flukeout

**Comment by raygervais** [comment]
@humphd, I'd like to take a crack at this enhancement. I believe I am proficient to attempt this.

**Comment by flukeout** [comment]
@raygervais - we don't really have anything to put in there at the moment, so I'm not sure if it's the best use of your time at this point. Do you have some ideas for how to use that space?

**Comment by humphd** [comment]
Let's start by making it visible only when a preference is set to `true` and by default we'll not show it.  The preference system is documented here https://github.com/adobe/brackets/wiki/Preferences-System, and I can help when you get that far.

To start, I'd just get it to show at all, and be resizable.  Then we can add the pref, figure out what to put in it, etc.

**Comment by raygervais** [comment]
I will work on that right away. I did have a few ideas for possible features which may fit the space well. Details on these ideas can be found [here](http://raygervais.ca/brackets-enhancement-proposal/). For a TLDR, here is the synopsis from the post describing two possible implementation ideas:

# Drag and Drop HTML Snippets
Following similar to XCode’s UI Creator, this area could house drag-drop templates for basic HTML code, with the option to extend with framework classes and various other snippets that may be useful in the future. This would allow Thimble to be more accessible to newer developers, while also providing good web standards. Furthermore, it may benefit the average developer looking to utilize Thimble beyond just a learning environment, and instead use it as a basic test environment for their code.

# Quick Settings Panel 
Access to the Editor’s settings, including tab spacing, typeset, syntax highlighting styles, and plugin support. This would tie in with the originally implemented preferences manager, allowing the user to custom tailor their experience on their development machine.This would be responsive, my suggestion on how to best utilize the space is to have three different width classes which would display the settings in the following manners:

    Icon Text: Value
    Text: Value
    Icon: Value

Using three different display manners would allow the application to determine which is best to use for the space, thus introducing a dynamic display which could adapt to different widths without changing the familiarity of the layout and icons. 

As you can see, I focused on enhancing thimble to be more useful beyond the learning phase of the developers experience with it. I look forward to any comments, opinions and criticisms on these ideas.

**Comment by humphd** [comment]
Love your post, great work.

Somewhat related, I notice that someone's got an extension for Brackets to make the extensions toolbar appear at the bottom of the editor:

https://github.com/dnbard/extensions-toolbar

**Comment by raygervais** [comment]
Thank you for the kind words, I'm glad you enjoyed my proposal post. I'm curious what your opinion is on my separate feature suggestions. I personally see the snippet / code template feature being more useful for the average programmer, since it's a rarity that one messes with their development environment to the point that I suggested. 

I have looked at the extension you recommended, and I'm curious if you'd like me to integrate something similar into brackets directly.

**Comment by flukeout** [comment]
Hi @raygervais thanks for the great writeup, some good thoughts in there. I definitely like the idea of snippets being in there more than the editor settings. The settings don't get used that often, so I think it's best we not clutter the view with them.

There is already an issue being worked on related to code snippets. It might make sense to wait until that work is done and then see if you can adapt it (or check in and collaborate).

Another use for it could be to add some kind of JS console.

Also, are there any useful actions that are related to files that we could put there? It has a really close proximity to the file view already.

Curious about your continued thoughts on this.

**Comment by raygervais** [comment]
Hi @flukeout, I'm glad that you agree with my statement regarding code templates being more useful than editor settings. I never considered a JS console, and I'm curious what the intended uses you could think of. I have rarely used a JS console, so I'll rely on your knowledge of functionality for that topic. 

One idea, which I'm not overly fond of simply because I would not know how to judge it's usefulness until a prototype is created, is to include in that space a quick access list to your other projects. At the moment, I can only think of spacemacs which follows something similar, which I've included below.

![](https://simpletutorials.com/uploads/d5c5e692-fe8c-11e5-a194-f23c91df6128/6.png)

I'm curious how we will go about this, in the mean time I'm looking forward to opinions and criticism, while also starting to flesh out the space itself in relation to responsiveness and styling.

**Comment by humphd** [comment]
I've suggested that @raygervais start by working on the "console in brackets" bug to get a feel for doing this kind of work, since it's better scoped, and less likely to frustrate him until we sort out what this bug wants to end up being.

**Comment by humphd** [comment]
I'm going to close this until we have a better understanding of what we'd do with it.  I think it's neat, but not overly useful.  We can open again if/when we know what we want.
