### ISSUE TITLE
Allow users to download individual file or folder structure without having to download the whole project.

### ISSUE THREAD

**Issue by simon66** [mozilla/brackets#596]
Feature first filed here mozilla/thimble.mozilla.org#1313 by @ScottDowne 

It would be amazing if brackets had an option to download individual file or folder structure without having to download the whole project.

Here are the behaviors for this new feature:

## Downloading a Single file
**UI**:
![download_file](https://cloud.githubusercontent.com/assets/1103528/23075578/123fcb86-f50b-11e6-9d0e-6db3788d226a.PNG)
**Expected behavior**: The selected file will be downloaded without it being zipped.

## Downloading a Folder
**UI:**
![download_folder](https://cloud.githubusercontent.com/assets/1103528/23075621/329f825e-f50b-11e6-9021-ce0e509c9989.PNG)
**Expected behavior:** This will zip the folder structure/contents and download it. The contents in the zip file will look like this: `{ folder name } / { file contents }`

If the folder is empty and the user chooses to download it, should an error message show or should the empty folder be zipped and downloaded? What do you think?

**Comment by humphd** [comment]
I'd recommend you make the context-menu string just say "Download" and then you don't need to figure out if its a file or folder in the UI.

I'd then consider reworking this function https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/ArchiveUtils.js#L145 so that you can pass a path instead of having it assume you want to zip the project root.  It should just "Do the Right Thing" if you pass it a file or folder.

I'm assuming you want to work on this, but let me know if I'm wrong.
