### ISSUE TITLE
Addin new use case to "dirtyFlagChange" 

### ISSUE THREAD

**Issue by Taguiar** [mozilla/brackets#607]
### What I propose to do.
As request by @humphd I will be adding a new feature to main.js allowing that a display icon is shown whenever a user is not logged in with his thimble account and its document are saved locally to the browser.

### Steps to Reproduce

1. User not logged in
2. Makes changes and wait for 5 minutes
3. Jump trough files

**Expected behavior:**
I want the user to be prompt whenever a save curr.

**Actual behavior:**
Nothing is displayed/ document is saved locally

### Versions
I will be using firefox and google chrome browsers to make sure the portability between browsers.

**Comment by humphd** [comment]
@Taguiar and I talked about this a bit, and the concept is to add an event (or events) to build UI in Thimble that mimics what Google Docs does:

![](http://www.laptopmag.com/images/wp/purch-api/incontent/2013/03/SS9_OfflineGDoc.jpg)

Essentially, we know when an editor is dirty, and when it gets saved, and could trigger events for either or both, allowing the hosting app to show UI to help a user know that things are saved locally.  This is not the same as syncing to the Publish server, which is a Thimble-only task, and done for authenticated users.

**Comment by Pomax** [comment]
interesting, I like this idea. Is there a possibility of sync-clobbering that we need to be careful with though? What if someone works on their laptop offline, then uses their desktop and starts editing a thimble only to realise they did way more work on their laptop, and then turns their laptop back on to make sure that data gets synced to the server instead? Which "updates" will win? (the desktop will have already pushed data to the server due to simply being online, so its files are "newer" but that does not mean they should win and override everything that user had done on their laptop)

**Comment by humphd** [comment]
NOTE: We make no guarantees about opening a project more than once, on same or on multiple computers.  This bug isn't really about that.  However, to answer your question (all of this relates to Thimble):

* if not logged in, every project is unique, you can't have multiple copies of it open
* if logged in, we try to send changes to the publish server for storage (i.e., whole file) when it is changed locally, and don't worry about consistency across clients: last save wins.
* when the app opens, if there are changes queued up that need to be sent to the server, we use those vs. what is on the server so we don't wipe out your pending work with what was last saved.

From a purely Brackets point of view, you are working on a shared filesystem.  If you have two tabs open that both edit the same directory, the Brackets code has code paths to deal with files changing on disk vs. what you have in the editor, and it will prompt you, and also uses filesystem watches to listen for changes to files.

**Comment by Pomax** [comment]
I know we don't. That's a failing on our part: it feels like we *need* to tackle that before we do this work. At the very least we need to let the user know that things are about to go potentially horrible wrong and put them in the driving seat for resolving versioning conflicts. I don't know where that's best filed: here, or on the thimble repo.

**Comment by humphd** [comment]
This bug is just an event to the hosting app regarding things that are happening now.  Let's untie these two discussions.

The overall goal of *this* bug is to make it possible for us to let a user know that their work has been "saved" at all.  Right now we have zero UI, which makes it seem odd to just close your browser tab.

**Comment by Pomax** [comment]
I can move all these comments to a new issue in the appriate repo - new issue here, or on thimble?

**Comment by humphd** [comment]
Thimble, I think. Brackets is just sitting on a "local fs" and already has enough baked into it to do what any regular editor would do sitting on a normal fs.  We probably need to evolve things at the level of the hosting app.

**Comment by Taguiar** [comment]
@flukeout do you have anything to say about the design?! Or should I go with whatever I decide?

**Comment by gideonthomas** [comment]
@Taguiar I think for now, let's figure out the Brackets side of this (which has zero design requirements) that deals with the events. Once that is setup (open up a PR), I think @flukeout can provide some design input in the mozilla/thimble.mozilla.org#1789 bug on how to surface these events to the user.

**Comment by flukeout** [comment]
@Taguiar @gideonthomas yeah that sounds good to me. When we're ready, I think we should use the space beside the project name. I'll help with design when we get to that stage.

**Comment by Taguiar** [comment]
@humphd I am having a problem tracking the events already established between thimble and bramble. Do you know where should I start looking for those events? like a file or a method so I can find out how it is supposed to be implemented!

**Comment by humphd** [comment]
It's complicated, I know.  It's always best to take an example, and there are a bunch you can study, see https://github.com/mozilla/brackets#bramble-instance-events.  Consider `sidebarChanged`:

* We define some methods that can be called internally in Brackets, and which trigger events out to Thimble: https://github.com/mozilla/brackets/blob/master/src/bramble/BrambleEvents.js#L45-L51

* Something happens with the sidebar in the Brackets code, and internal events are fired via our methods above: https://github.com/mozilla/brackets/blob/master/src/view/WorkspaceManager.js#L285-L291

* Then, we have code that listens for the above event to happen, and it re-fires it across to Thimble: https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteEvents.js#L60-L66

It's more complicated than it should be, because we're working between Brackets core code, a Brackets extension, and an unrelated JS library connected to Thimble.  But if you copy that style, and study the other events and how they are made, you'll get the idea.

**Comment by humphd** [comment]
![dirty-saved](https://cloud.githubusercontent.com/assets/427398/23480138/db63e01e-fe94-11e6-9e8d-9a1ed309cc1e.gif)

I was watching how GDocs does this today, and they constantly spam you with "Saving..." and "Saved" style text, and it has never bothered me.  So I think we will be able to do something similar and not annoy people, if we keep the text light and small like they do.

Obviously this bug is about the events to make that possible vs. the UI.  But I wanted to get people on the same page.

**Comment by humphd** [comment]
Here's what Medium does, as another example:

![medium-example](https://cloud.githubusercontent.com/assets/427398/23961907/c92d2934-0982-11e7-9c69-6fb44841ab14.gif)

I kind of like their 3-state text indicator, it's comforting.

**Comment by humphd** [comment]
Fixed by https://github.com/mozilla/brackets/pull/632, moving discussion to https://github.com/mozilla/thimble.mozilla.org/issues/1526 for the UI changes.
