### ISSUE TITLE
Do you need an automated code style review tool?

### ISSUE THREAD

**Issue by tgrundmanis** [mozilla/brackets#825]
Myself and a cofounder created a style linter developer tool that comments on style errors in GitHub pull requests (for 15 languages and counting). It is free for open source projects.

You can check out the product on https://stickler-ci.com. Just authorize your GitHub account, enable a public repo, and then open/update an existing pull request (or create a new pull request).

**Comment by ryanwarsaw** [comment]
There are better ways to get your product out there and promote it than to go down a list of Mozilla repositories and spam them with the same issue repeatedly. Also you might want to check out a tool called "prettier", I don't understand what the purpose of Stickler is since that's the future anyways.

Closing and locking for spam.

**Comment by gideonthomas** [comment]
@ryanwarsaw do you have links to other repositories where this has been done?
